if(TARGET EchHttp::curl)
  return()
endif()
get_filename_component(_eh_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
foreach(_eh_lib curl ssl crypto zlib)
  add_library(EchHttp::${_eh_lib} STATIC IMPORTED)
  if(WIN32)
    set(_eh_path "${_eh_root}/lib/${_eh_lib}.lib")
  else()
    set(_eh_path "${_eh_root}/lib/lib${_eh_lib}.a")
  endif()
  set_target_properties(EchHttp::${_eh_lib} PROPERTIES
    IMPORTED_LOCATION "${_eh_path}"
    INTERFACE_INCLUDE_DIRECTORIES "${_eh_root}/include")
endforeach()
find_package(Threads REQUIRED)
set_property(TARGET EchHttp::curl PROPERTY INTERFACE_COMPILE_DEFINITIONS CURL_STATICLIB)
set_property(TARGET EchHttp::curl PROPERTY INTERFACE_LINK_LIBRARIES EchHttp::ssl EchHttp::zlib)
set_property(TARGET EchHttp::ssl PROPERTY INTERFACE_LINK_LIBRARIES EchHttp::crypto)
set_property(TARGET EchHttp::crypto PROPERTY INTERFACE_LINK_LIBRARIES Threads::Threads)
if(WIN32)
  set_property(TARGET EchHttp::crypto APPEND PROPERTY INTERFACE_LINK_LIBRARIES bcrypt advapi32 crypt32 ws2_32 iphlpapi)
elseif(ANDROID)
  set_property(TARGET EchHttp::crypto APPEND PROPERTY INTERFACE_LINK_LIBRARIES c++_static c++abi atomic m ${CMAKE_DL_LIBS})
elseif(UNIX AND NOT APPLE)
  set_property(TARGET EchHttp::crypto APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${CMAKE_DL_LIBS} m)
endif()
